version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80

  django_container_gunicorn:
    image: django_test_image:9
    networks:
      - network
    volumes:
      - static-volume:/home/toyproject/staticfiles
      - media-volume:/home/toyproject/media
    secrets:
      - MYSQL_PASSWORD
      - django_secret_key

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-db:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD


networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-db:

secrets:
  django_secret_key:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true