# Generated by Django 4.1.1 on 2022-10-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
